### ISSUE TITLE
lantrigger not on TAustin Shared Projects

### ISSUE THREAD

**Issue by sgraystar** [toddaustin07/lantrigger#1]
Hi Todd,
I was hoping to try lantrigger/edgebridge to control some hub connected switches, but it does not appear on your channel. Is it superseded? Withdrawn?
Cheers

**Comment by toddaustin07** [comment]
Hi there!  Yes, that's strange; not sure how it got removed.  I just added it to my shared projects channel, so try again.  I haven't touched this project in a while, so let me know if you run into any issues.  I'll retest it myself when I get a chance this weekend to make sure I didn't leave anything hanging.

**Comment by toddaustin07** [comment]
FYI, just did a quick test and it's working as expected.

**Comment by sgraystar** [comment]
Thanks! Will give it a try.

**Comment by sgraystar** [comment]
All working, fantastic.
FYI we have an older home automaton system that controls pool/spa pumps by HTTP, and this allows a simple changeover to a more robust hub and z-wave switches with local execution.
When I couldn't find it initially I thought maybe you had decided to allow your vEdge Creator devices to register with edgebridge...
Thanks again. Do you have a buy a coffee anywhere?
Cheers
